name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Restart Docker
        run: |
          sudo /usr/local/bin/docker-restart.sh
          sleep 10

      - name: Login no GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Para containers antigos
        run: |
          docker compose down || true

      - name: Build da imagem
        run: |
          docker build -t ghcr.io/strelogg/sua-api:latest .

      - name: Push pro ghcr.io
        run: |
          docker push ghcr.io/strelogg/sua-api:latest

      - name: Cria o .env na VM
        run: |
          cat > .env << EOF
          DB_HOST=postgres
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          DB_NAME=${{ secrets.DB_NAME }}
          NODE_ENV=production
          PORT=6060
          JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
          EOF

      - name: Sobe com Docker Compose
        run: |
          docker compose up -d --build

      - name: Verifica se subiu
        run: |
          sleep 10
          docker compose ps